<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Xylab.Management.Kudu</AssemblyName>
    <RootNamespace>Xylab.Management</RootNamespace>
    <NoWarn>$(NoWarn);SYSLIB0013</NoWarn>
    <Description>Useful tools from ProjectKudu including VirtualFileSystem</Description>
  </PropertyGroup>

  <Import Project="..\..\build\NugetPackage.props" />

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="System.IO.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <None Include="LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
