<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>SatelliteSite</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SatelliteSite.Substrate" />
    <PackageReference Include="SatelliteSite.HostBuilder" />
    <PackageReference Include="SatelliteSite.IdentityModule" />
    <PackageReference Include="XiaoYang.EntityFrameworkCore.Bulk.SqlServer" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jobs.Module\Workflows.Legacy.Module.csproj" />
  </ItemGroup>

</Project>
