<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Xylab.Management</RootNamespace>
    <UserSecretsId>f9f8f9c1-7623-4a6b-9433-b7e2f0a09f2b</UserSecretsId>
    <NoWarn>$(NoWarn);MSB3246</NoWarn>
  </PropertyGroup>

  <Target Name="SetGitInformationalVersion" AfterTargets="InitializeSourceControlInformation" BeforeTargets="GetAssemblyAttributes">
    <ItemGroup>
      <AssemblyMetadata Include="GitCommitId" Value="$(SourceRevisionId)" Condition="'$(SourceRevisionId)' != ''" />
      <AssemblyMetadata Include="GitBranchName" Value="$(SourceBranchName)" Condition="'$(SourceBranchName)' != ''" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Management.Interop\Management.Interop.csproj" />
    <ProjectReference Include="..\Management.ProjectKudu\Management.Kudu.csproj" />
    <ProjectReference Include="..\PowerShell.Cmdlets\PowerShell.Cmdlets.csproj" />
    <ProjectReference Include="..\PowerShell.WebService\PowerShell.WebService.csproj" />
    <ProjectReference Include="..\Workflows.LogicApps\Workflows.LogicApps.csproj" />
  </ItemGroup>

</Project>
