<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <AssemblyName>SatelliteSite.JobsModule</AssemblyName>
    <DescriptionAttach>The job module</DescriptionAttach>
  </PropertyGroup>

  <Import Project="..\..\build\NugetPackage.props" />

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="SatelliteSite.StaticWebAssets.JsonViewer" />
    <PackageReference Include="SatelliteSite.Substrate" />
    <PackageReference Include="SatelliteSite.IdentityCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jobs.Abstraction\Workflows.Legacy.csproj" />
  </ItemGroup>

</Project>
