<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>Xylab.Remoting.PowerShellClient</AssemblyName>
    <RootNamespace>Xylab.Remoting.PowerShellClient</RootNamespace>
    <PackageId>Xylab.Remoting.PowerShellClient</PackageId>
    <Description>PowerShell client for remote management</Description>
  </PropertyGroup>

  <Import Project="..\..\build\NugetPackage.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="System.Management.Automation" />
  </ItemGroup>

</Project>
