<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Xylab.Management.WebService</AssemblyName>
    <RootNamespace>Xylab.Management</RootNamespace>
    <PackageId>Xylab.Management.WebService</PackageId>
  </PropertyGroup>

  <Import Project="..\..\build\NugetPackage.props" />

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Management.Interop\Management.Interop.csproj" />
  </ItemGroup>

</Project>
