<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>Xylab.Management.Automation.Cmdlets</AssemblyName>
    <RootNamespace>Xylab.Management.Automation.Cmdlets</RootNamespace>
    <PackageId>Xylab.Management.Automation.Cmdlets</PackageId>
  </PropertyGroup>

  <Import Project="..\..\build\NugetPackage.Backend.props" />

  <ItemGroup>
    <PackageReference Include="System.Management.Automation" />
  </ItemGroup>

</Project>
