<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>Xylab.Management.Automation.Cmdlets</AssemblyName>
    <RootNamespace>Xylab.Management.Automation.Cmdlets</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management.Automation" />
  </ItemGroup>

</Project>
